### ISSUE TITLE
Bump otter-grader to 0.1.2

### ISSUE THREAD

**Issue by chrispyles** [berkeley-dsep-infra/datahub#1157]
Hey is it possible to bump the version of otter-grader on Datahub to 0.1.2? We have a notebook deploying in Data 88 in about a week that requires features from this version.

**Comment by felder** [comment]
Done.

**Comment by felder** [comment]
Unfortunately this upgrade breaks ok py which is used for grading by data8.  As I understand it otter-grader has a dependency on gofer and gofer conflicts with ok py.  As a result I had to switch the version of otter-grader back to 0.0.10

@Yanay1 indicated that the issue is with otter-grader and said that his team would handle it.  When we move to upgrade this again, we'll test via a notebook in staging first.

**Comment by chrispyles** [comment]
@felder sorry about this! We didn't realize that the gofer client package would mask okpy's client package. We've just released otter-grader 1.0.3 which no longer imports or requires gofer to be installed.

Please test at your leisure and let us know if it has any other issues.

Thanks!!

**Comment by felder** [comment]
Initial tests with a manual install in staging look good.  I have several meetings in the early afternoon.  After those, I'll upgrade otter-grader, deploy to staging, and invite @Yanay1 and Annie to test.

**Comment by felder** [comment]
@chrispyles you mean otter-grader 0.1.3 right?  Also should I upgrade to 0.1.5 which was just released 2 hours ago?

https://pypi.org/project/otter-grader/0.1.5/

**Comment by chrispyles** [comment]
Yes, any version >= 1.0.3 works. 1.0.5 has some bug fixes from other features that aren't relevant to use on DataHub, but that version also doesn't rely on gofer, so either is fine. If you've already started testing of 1.0.3, stick with that to make it easier.

**Comment by felder** [comment]
Tests on staging look good.  Deploying to prod.

**Comment by felder** [comment]
Deployed to prod.
