### ISSUE TITLE
Duplicate student pod naming on data100 hub 

### ISSUE THREAD

**Issue by wwhuang** [berkeley-dsep-infra/datahub#1318]
We had a student get a pod naming conflict error when booting up data100 hub. This was resolved by having the student manually shut down and re-launch their server. 

![image](https://user-images.githubusercontent.com/2029851/74391318-b4270a00-4db8-11ea-8e95-b2a705a49303.png)

**Comment by yuvipanda** [comment]
I saw a bunch of other pods in 'Evicted' state around this time, from lack of disk space - probably from the fact that our images are massive. But this needs more investigation - looks like the pod itself was killed (since otherwise k8s wouldn't let this happen), but somehow the docker container on the node wasn't...

**Comment by yuvipanda** [comment]
This hasn't happened in a while, so I think we're good. We can re-open if needed.
