### ISSUE TITLE
Data100 Autograder Scaling

### ISSUE THREAD

**Issue by wwhuang** [berkeley-dsep-infra/datahub#1359]
I have fixed the Data100 autograder issues such that we have autograder pods that loop, rather than spinning up a new one per assignment grading request, which caused memory usage issues. 

Currently, the autograder is limited to 12 GB memory, and I would like to scale it up. The key issue is that Okpy gives the autograder timed access tokens, so the autograder cannot take all night to run. 

A few questions
1) Would it be possible to give the autograder timed resource usage? For example, if we ran the autograder at night, could it use more memory, and then at 7 am we just forcibly delete any outstanding autograder jobs?  

2) How exactly do memory limits and k8s pods work? If it runs out of memory, does k8s "freeze" the pod, or does it kill it? Should the number of k8s pods I have running at any given moment be based on their initial memory request, or the maximum amount of memory each pod can request?

**Comment by yuvipanda** [comment]
Thanks for opening this, @wwhuang!

Some documentation about memory limits is at: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run

In particular, 

> If a Container exceeds its memory limit, it might be terminated. If it is restartable, the kubelet will restart it, as with any other type of runtime failure.

Is it possible to re-request a token from okpy? I don't feel super comfortable with a manually run process that could take over the whole cluster, since bugs there are likely to affect other users of the hubs.

One possibility might be that we have an entirely separate cluster, that can scale down to 0, just for this. However, I don't think we have the resources to support it between me and @felder. So you'd have to manage it, make sure it has scaled to 0 when not in use, and not take up too much resources - since accidentally leaving it running can cost a lot of resources! However, I don't know how much money this will cost. We can trial this for a few weeks and see how it goes? Then we can do a quick cost estimate, and involve appropriate people to see where this should go.

/cc @ericvd-ucb who might be interested.

**Comment by wwhuang** [comment]
Okay it took a while, but we got longer lived access tokens for the data100-grader. Everything seems to be working right now with our current resource allocation, so I'm gonna close this.

**Comment by yuvipanda** [comment]
Thanks for dealing with this, @wwhuang!
