### ISSUE TITLE
Set up regular snapshots of data8x homedirs volume

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#1454]
We run our own NFS server for data8x now. The disk is a single volume to make cloud provider snapshots easier. We should make sure that happens on a schedule.

**Comment by felder** [comment]
snapshot best practices:
https://cloud.google.com/compute/docs/disks/snapshot-best-practices

**Comment by felder** [comment]
So on experimenting with scheduled snapshots, it turns out that as far as I can tell all snapshots of a persistent disk are incremental.  This includes both ones taken manually and ones taken via the schedule.  Taking them is virtually instantaneous and does not impact performance.

Disks can only have a single snapshot schedule attached to them.  I've decided to try one snapshot every 12 hours with deletions of old snapshots after 7 days.

As older snapshots are deleted, the data that the later dependent snapshots require is automatically moved to the next snapshot.  

While I want to keep an eye on this process I suspect that more frequent snapshots with longer retention is not going to result in a much greater data usage than less frequent ones or a shorter retention.  Exceptions to this might be if a large amount of data is deleted.  In which case we could manually delete the snapshots that contain the extra data.

Another thing to note is that the snapshots take up considerably less space than the data.  Right now the snapshot is about 1/4 - 1/3 the utilized disk capacity...500gb vs 1.8TB.

Pretty cool!

**Comment by felder** [comment]
This has been running for some time and seems to be working out.
