### ISSUE TITLE
Request python package for PHYS188/288 - similar to #1073

### ISSUE THREAD

**Issue by ybh0822** [berkeley-dsep-infra/datahub#1842]
Hello,

Hope this finds you well. This request is related to #1073 
Apologies for the trouble; this package is still not ready to be released via pypi. Would it be possible to put it in some build directory e.g. /srv/app/venv/assignment-1910 (just like last year)? 

**Which package do you want installed?**
https://github.com/HerculesJack/assignment-1910

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
datahub.berkeley.edu

**Which class will use this package?**

Physics 188/288 (https://classes.berkeley.edu/content/2020-fall-physics-188-001-lec-001)

**Which semester will this package be used for?**
Fall 2020

I sincerely appreciate your help and consideration.

**Comment by felder** [comment]
@ybh0822 Looking at #1073 I see that assignment-1910 is still being deployed.
https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/images/default/connectors/2019-fall-phys-188-288.bash

From an open terminal in my own pod:
```
$ echo $CONDA_DIR
/opt/conda
$ cd /opt/conda
$ ls -ld assignment-1910
drwxr-xr-x 6 jovyan jovyan 4096 Sep  7 20:44 assignment-1910
$ cd assignment-1910
$ ls
bayesfast  cosmofast  data  install.sh  LICENSE  planck.ipynb  readme.md
$ pwd
/opt/conda/assignment-1910
$
```
Since I'm not familiar with this package, based on that info can you let me know what else needs to happen here?

**Comment by felder** [comment]
Closing issue.  Please reopen if necessary.
