### ISSUE TITLE
Tab complete and command history in terminal 

### ISSUE THREAD

**Issue by connorbybee** [berkeley-dsep-infra/datahub#1890]
It appears the tab completion and command history options in terminal are not enabled in biology.datahub or datahub. In biology.datahub, those features were working until today.

**Comment by d-alex-hughes** [comment]
@connorbybee which shell are you in? 

I'm sorry that I'm not on the biology.datahub, but I've seen this issue previously when there has been a change from bash away to another shell as the default. 

To get to a bash shell, issue `bash` at the CLI prompt.

**Comment by felder** [comment]
Note that in #1865 @yuvipanda mentioned we should just remove the config.

So it may be that we go with the last option which is do nothing, but even so I think "nothing" in this case should be applied consistently so that users in general get the same default shell regardless of which hub the are working in.

**Comment by connorbybee** [comment]
> @connorbybee which shell are you in?
> 
> I'm sorry that I'm not on the biology.datahub, but I've seen this issue previously when there has been a change from bash away to another shell as the default.
> 
> To get to a bash shell, issue `bash` at the CLI prompt.

Great! I didn't notice bash wasn't default.

**Comment by yuvipanda** [comment]
Thanks for opening this, @connorbybee!

#1908 should set this to bash for all hubs...
