### ISSUE TITLE
Request more ram for datahub instances for students in ENVECON153

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/datahub#2013]
ENVECON153 (EEP153) has an enrollment of about 50 students; part of the plan involves analysis of datasets which are too big for the default provisioning.   

Experiments suggest that if instances had 4GB of ram that would be adequate.

**Comment by felder** [comment]
This change is on its way to prod.

**Comment by ligon** [comment]
This change seems not to have carried over into 2022--students have instances with 1 GB of RAM.  Can we re-up to 4GB?

**Comment by felder** [comment]
@ligon Can you please open a new issue using the issue template for this?

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&template=higher-resources.md&title=Request+more+RAM+for+class+X

These changes will not carry over because they are based on specific values for each term and year including the courses' SIS ID which changes every semester.  This means every semester you'll need to put in a request.  

Alternatively depending on use case, it may make sense to have a separate hub.
