### ISSUE TITLE
Request R package LFE for class R hub EEP 118

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#2239]
**Which package do you want installed?**
lme
**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
EEP 118
Include a link to appropriate entry in https://classes.berkeley.edu/ if available. If not, please mention class name & instructor.
https://classes.berkeley.edu/content/2021-spring-envecon-c118-001-lec-001
**Which semester will this package be used for?**
Sp 21 - but this course is taught continuously 
This helps us clean up unused packages after a term ends.

**Any additional information we should know about?**
This used to be available but somehow got dropped

**Comment by yuvipanda** [comment]
@felder can you take this on?

**Comment by felder** [comment]
@yuvipanda sure!

Also chatting with @ericvd-ucb there's a bit of confusion about what needs to be installed, so we'll get that cleared up first.

**Comment by ericvd-ucb** [comment]
Hi - sorry I messed up @felder the package is lfe   - an R package
https://cran.r-project.org/web/packages/lfe/index.html
Apologies for the confusion

**Comment by felder** [comment]
@ericvd-ucb 

In the description for that package, this is a bit ominous:

"WARNING: This package is NOT under active development anymore, no further improvements are to be expected, and the package is at risk of being removed from CRAN."

If CRAN pulls it, this is going to cause builds to fail.  I've asked Eric to mention this to the professor because it may be wise to consider another package if this one is EOL.
