### ISSUE TITLE
[urgent] virus installed on PC 

### ISSUE THREAD

**Issue by aveysongco28** [berkeley-dsep-infra/datahub#2311]
Hi,

ReverceCaptcha Virus was installed on my PC and I need it removed. The virus pops up ads stating I have 5 viruses and need to remove it by purchasing virus programs (I have not purchased anything). I was advised to wipe my PC due to potential of backdoors being created to infect my PC. It happened when I was accessing the UC Berkeley Data Hub to work on my assignment on Jupyter. Please let me know if you all can help because I am not sure if this is associated with the massive dat breach and I have a lot of sensitive information on my PC ):

**Comment by yuvipanda** [comment]
Heya! Thanks for letting us know, and really sorry about your PC infection. Unfortunately, we can only provide support for things happening on the datahub cluster itself, so we can not offer any help for this situation. 

If this is a university provided machine, https://technology.berkeley.edu/contact-us might be able to help. Otherwise, I'm not sure what we can do. Sorry!

I hope you can  recover your PC!
