### ISSUE TITLE
Set up gofer-grader for data8x

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#475]
Tracking task for setting up gofer-grader on data8x.

- [x] Install gofer-grader package into image (Yuvi)
- [x] Install gofer-grader nbextension into image (Vincent)
- [x] Create new VM that can be used for grading (Yuvi)
- [x] Setup gofer-grader inside this VM (Vincent)
- [x] Make gofer-grader service inside VM a JupyterHub service (Yuvi)

**Comment by yuvipanda** [comment]
This time, the hub is properly managed with continuous deployment from this repository, with config and images under https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/data8x/.

@vipasu I've set you up for two tasks here:

1. Setting up the nbextension. You'd probably need to modify files in here: https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/data8x/image to set it up. `requirements.txt` lets you install python packages, and `postBuild` lets you run arbitrary commands. You can also distribute nbextensions alongside your python package, which is the preferred method - see https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html. 

2. Setting up gofer-grader service in a VM. I've created a VM (`grader`) in which you can set up gofer-grader as you wish. Am happy to help, since I think setting up the external JupyterHub service will require changes to this repo.

**Comment by vipasu** [comment]
Thanks for setting this up! 

Quick questions: when packages are installed from requirements.txt is there a default place or environment variable that references where they get installed?

**Comment by ryanlovett** [comment]
@vipasu According to repo2docker source, the root of the python dir is ${CONDA_DIR}, /srv/conda.

**Comment by vipasu** [comment]
Just to post an update here: #493 adds the nbextension to requirements.txt which has source [here](https://github.com/data-8/gofer_submit). However, there's an asterisk here in that the end point the extension sends files to has to be changed once we have the grading server up.

Next I'll be working on separating the gofer service (e.g. server that accepts notebooks, saves them, and grades them) so that it can just be installed on its own as well and put it on `grader`. Will ping again when I'm done with that.

**Comment by yuvipanda** [comment]
@vipasu I merged #493, so it should be on the data8x hub now.

**Comment by yuvipanda** [comment]
>     * I'm also keeping a csv log of all grades. However, it's currently appending to a csv file. Is there a better way to do this to ensure that the file doesn't get corrupted or have conflicting versions?

I'd recommend using a database like sqlite. CSV files will probably get corrupted.
 
>     * is there anything else that I'm missing before I can ask for your help to make it an external jupyterhub service?

You should set up the service so it keeps running regardless of system restarts. I'd recommend looking at systemd for this.

**Comment by vipasu** [comment]
> I'd recommend using a database like sqlite. CSV files will probably get corrupted.

Thanks. I've made it so that grades are saved to a database and there's a script to write the database information to csv.

> You should set up the service so it keeps running regardless of system restarts. I'd recommend looking at systemd for this.

I believe I implemented this properly with two files, but am not fully sure how to test

- gofer_service/startup.sh 

this sources the virtualenv for the service and makes the python call to start it. 

- /etc/systemd/system/gofer.service

points to the location of `startup.sh` and has restart = always.

**Comment by yuvipanda** [comment]
@vipasu cool! I think when we set it up, the service will still be available at the same URL as before - the hub will set it up at hub.data8x.berkeley.edu/<servicename>.

**Comment by vipasu** [comment]
@yuvipanda are you referring to the IP address of the test hub? I will need to put that in by hand since before it just had the relative local path (/services/gofer_nb) without the address. 

Also occurred to me that another todo item is getting the LTI credentials loaded on `grader`. I might need a refresher on where the LTI config is to put them in a file. Then it will be easy to add a line to the startup.sh to source those as well.

**Comment by yuvipanda** [comment]
@vipasu Can you tell me where gofer is currently running? I don't see the process running

**Comment by yuvipanda** [comment]
@vipasu I made the suggested changes to startup.sh in the repo manually, and also made a PR: https://github.com/data-8/gofer_service/pull/1

With this, I could start the service, and pressing 'Submit' seems to send a request to the gofer grader successfully (I could verify this with `sudo journalctl -u gofer -f` on `grader`).

However, gofer seems to return a 404. Hope you'll be able to debug that.

I left appropriate credentials in `/etc/gofer-creds`.

**Comment by vipasu** [comment]
Thanks for figuring those out - I had to drive to Santa Barbara for a tournament.

I was able to figure out what was going on with the 404. Even though the configuration file links grader at /services/gofer_nb/, the post request looked like it was hitting the grader also at /services/gofer_nb/ instead of at the root of grader.

However, a new issue arises because of (I believe) the hub auth part where it tries to talk to the hub. 
> [E 190126 07:05:01 auth:283] Error connecting to http://127.0.0.1:8081/hub/api: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /hub/api/authorizations/cookie/jupyterhub-services/2%7C1%3A0%7C10%3A1548483540%7C19%3Ajupyterhub-services%7C44%3AZTViYmUyMjU5NTQ5NGZkN2I4Zjk4NTBjMGZlMTc4Yjk%3D%7Cccfc2c5b64f63c5fb302734f46d3c68784575d59718f1f962bd966796008d604 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0688ca7b8>: Failed to establish a new connection: [Errno 111] Connection refused',))
[W 190126 07:05:01 web:1667] 500 POST /services/gofer_nb/ (10.12.2.9): Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: grader)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub

Should this basically be hub.data8x.berkeley.edu/hub/api? If so, where is the best place to declare the c.JupyterHub.hub_ip variable?

**Comment by vipasu** [comment]
Thanks for figuring those out - I had to drive to Santa Barbara for a tournament.

I was able to figure out what was going on with the 404. Even though the configuration file links grader at /services/gofer_nb/, the post request looked like it was hitting the grader also at /services/gofer_nb/ instead of at the root of grader. That along with properly sourcing the jupyterhub credentials you provided seems to solve that issue!

Now I need to set up the docker image, copy the clean versions of directories and tests over, and place the edx config file for resource ids.

**Comment by vipasu** [comment]
Okay looks like things are running pretty smoothly! Got the docker image set up and the submit button results in labs being graded in the docker containers. They are also currently running as a systemd service.

The last step is sending grades back to EdX. I think I have gathered the sourcedid's for assignments (thanks to Alan) in the correct place, but I can't seem to recall where outcomes url is found on the courses. @yuvipanda could you help me locate these for the three sections? I'm not sure where is the best place to communicate it since it is sensitive information, but the file location is /home/vipasu/x19_config.json

**Comment by vipasu** [comment]
I remembered that there was a way to see it from the logs of the jupyterhub. However, I think the outcomes url are not set to the correct values because the edx course hasn't officially launched. The structure of the url is noticeably different in that it has a "preview" in it as of right now since it's before the launch date. Will check back in the morning

**Comment by vipasu** [comment]
The one that seems the most natural extension would be to make more space in the configuration file for different courses since it’s just a big JSON file. However, this could get messy since multiple people would be accessing the same file for multiple courses (which introduces room for more error). 

Another thought would be to run multiple gofer service instances with separate configurations. For example, I noticed there was a file that specified the port of the service at 10101 but there could be another instance of the service at, say, 10102.

**Comment by yuvipanda** [comment]
@vipasu cool. Let me know what you decide to do and how I can help!

**Comment by yuvipanda** [comment]
@vipasu am gonna close this as done. Feel free to re-open or make a new issue if needed.
