### ISSUE TITLE
data100 user timeouts 

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#480]
On day 1 of Data 100 ([hub repo](https://github.com/berkeley-dsep-infra/data100-19s)), a few users reported 5xx errors. Two users reported seeing "service unavailable". I'm going to upload various logs and events to some protected storage and link to it here. If/when this is analyzed, anonymized info can be put in this issue.

**Comment by yuvipanda** [comment]
Me and @ryanlovett spent lots of time on this yesterday. Our current hypothesis is that we have way too many NFS mounts per node, since there's a new mount per user - turns out about 4 including bind mounts. We've switched to using the same per-node NFS Mounter we are using in DataHub, and hopefully that'll be good enough.

**Comment by ryanlovett** [comment]
We now think the real fix was to [alter a k8s load balancer url](https://github.com/berkeley-dsep-infra/data100-19s/issues/41#issuecomment-459443680).
