### ISSUE TITLE
Provide extra RAM for module developers

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/datahub#557]
To help figure out how much RAM individual modules need, we should give the folks running module development more RAM.

Afaik, this currently includes 

- @erikvd-ucb
- Keeley (GitHub?)

Let's give 'em 4G of guaranteed RAM if we haven't already.

**Comment by ryanlovett** [comment]
I think the difference should be underscored somehow because it is easy to forget about the higher ceiling (at least, I've forgotten about my user's setting a time or two). Otherwise they might be surprised to find that their own notebooks work fine but fail in student servers. This is probably more of an issue for new instructors (not module developers) rather than those who are perpetually involved like Eric and Keeley.

I'm not sure what the solution is, other than perhaps "test your notebooks in a regular/test user's account too".
