### ISSUE TITLE
Set up a hub for Genomics Class

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/datahub#648]
Hi there 
Met with Prof Sudamat and GSI Pomerantz
about a summer genomics class

They will need 
- whitelist of 15 students + 3 instructors for 4gb
- set of genomics packages installed
- way to read in large datasets

Details to follow

**Comment by ericvd-ucb** [comment]
for now we would like to request

whitelist to 4gb for: 

pomerantz_aaron@berkeley.edu

--
and he would like to install  the following packages:
( and he can potentially test them on staging) 

Minibar: https://github.com/calacademy-research/minibar

Porechop: https://github.com/rrwick/Porechop

Seqtk: https://github.com/lh3/seqtk

AlleleWranger: https://github.com/transplantation-immunology-maastricht/allele-wrangler

Minimap2: https://github.com/lh3/minimap2

Racon: https://github.com/isovic/racon

Miniasm: https://github.com/lh3/miniasm

Wtgb2: https://github.com/ruanjue/wtdbg2

**Comment by yuvipanda** [comment]
Great, we can do this.

Can you tell us:

1. How big this data is?
2. How is it going to be produced?
3. How is it going to be read by the students? I'm guessing as files?
4. How often is this going to change?

**Comment by yuvipanda** [comment]
Is this course just for the summer, or is it also going to be run next fall? I think I'd like this to be its own hub for the summer, just to simplify things.

**Comment by yuvipanda** [comment]
A lot of these packages also seem to be not python packages, and have somewhat complex installation instructions. Do you think the professor or the GSI would be able to help us with installation? We'll be able to do it only once when building the image, so it shouldn't be too much of a pain

**Comment by ericvd-ucb** [comment]
@apome is the GSI we need to work with
And yes he should be involved here

Yes I looked through the packages as well - only a few of them have "pip install" directions

The data as -  I understand it - goes from a sequencer into some HPC processing at Savio - then gets saved out as files in the 0.5 to 10 GB range - these will change as some of the data will be from a field experiment

**Comment by yuvipanda** [comment]
@ericvd-ucb cool! Hi @apome :) Welcome to the datahub infrastructure! 

Do you know how often the data is gonna change, approximately? 5-10 times a semester, or 500-1000 times a semester? That'll help me figure out what kinda solution is appropriate.

**Comment by apome** [comment]
Hi there @yuvipanda! Thanks for your help. Yes for this first class we'll produce DNA sequence datasets with nanopore, resulting in fastq/fasta files for the students to process. Per your question of how often the data will change - are you referring to the files produced from DNA sequencing? I imagine the low end (5-10 times) rather than 500-1000 times. Please let me know if I can clarify anything / provide any additional info!

**Comment by yuvipanda** [comment]
Thanks @apome, that's very useful. Can you also tell me if this is a large number of small files or a small number of large files?

Can you also tell me if there is a course identifier for this yet?

Excited to get this going :)

**Comment by apome** [comment]
Ok great! It will likely be a large number of small files (e.g. hundreds of small files of DNA sequences - although these could be concatenated into one large file). 

There isn't a course identifier for this yet that I'm aware of - it's a bit of a pilot program through the Department of Integrative Biology. We have 16 undergraduate students who have signed up and this is being coordinated by Mark Jenkinson (https://mcb.berkeley.edu/directory/search/detail/6776) - if we need to set up a course identifier please let me know and I'll touch base with Mark about that. 

Thanks again and speak soon,

**Comment by yuvipanda** [comment]
@apome cool! No need for identifier, I'll just call config around this 'genomics-su19' for now. I'll keep this issue posted - hopefully I'll have something up shortly.

**Comment by apome** [comment]
Ok great, thanks @yuvipanda!

**Comment by apome** [comment]
Hi @yuvipanda hope all is well. Just wanted to touch base if installation of the packages seems ok or if I can provide any additional info. Thanks and catch up soon!

**Comment by yuvipanda** [comment]
@apome heya! we've been a little caught up. What is your timeline like? When does your class start?

**Comment by apome** [comment]
Not a problem @yuvipanda. The class starts on May 20, so we still have time :)

**Comment by yuvipanda** [comment]
@apome thank you for your patience! There's now a staging server at http://genomics-su2019-staging.datahub.berkeley.edu. Almost all the packages requested have been installed - see https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/genomics-su2019/image/postBuild for the script that is doing the installation. In the future, you'd probably make a pull request here with modifications if necessary to install more software packages.

I wasn't able to install https://github.com/transplantation-immunology-maastricht/allele-wrangler since it requires python2. Is it ok if we skip that one? Or is that a fundamental part of the class?

We should be able to give accounts 4G of memory once we set up production, hopefully tomorrow.

Take it for a spin and let us know if the software works ok. You can use the terminal from inside Jupyter (New -> Terminal) if you want a commandline to work with.

**Comment by yuvipanda** [comment]
Alright, genomics-su2019.datahub.berkeley.edu has been set up. User pomerantz_aaron has 4G of RAM. Let us know how we can help :)

**Comment by apome** [comment]
Hi @yuvipanda thanks so much for the help! I'm running through the pipelines now and so far most are looking good. 

I've encountered one issue with minimap2 - it appears to begin but after a few minutes the run says 'killed' - is this potentially an issue with memory?

Thanks again for the installations - I'll have to modify the protocol a little bit to get around AlleleWrangler not being installed (since it needs python2). As a workaround I'm thinking we can install https://github.com/asrivathsan/miniBarcoder and MAFFT https://mafft.cbrc.jp/alignment/software/ as a replacement.  
For making new pull requests for new installations in the future, what options should I select choose different branches/forks? 

Thanks again and speak soon,

<img width="1008" alt="Screen Shot 2019-05-07 at 12 52 18 PM" src="https://user-images.githubusercontent.com/26755340/57328940-9dd07d00-70c7-11e9-8c07-ef17bcf4b272.png">

**Comment by yuvipanda** [comment]
@apome glad it works! The 'killed' message makes me think it's memory related. On the top right in your notebook, it should show you how much memory you have access to, and how much you are currently using. I'm happy to bump it up if needed.

Unfortunately https://github.com/asrivathsan/miniBarcoder also is python2, while MAFFTT looks much easier.

For a pull request, I'd suggest forking the repository, making the changes to your repository and then making a pull request against the 'staging' branch here. Let me know if you need more information.

**Comment by apome** [comment]
Fantastic, thanks @yuvipanda. Yes I think you were right about the memory issue with minimap2. I ran it with a smaller dataset and it worked.

Ok so for MAFFT I'm actually a little uncertain the best way to install since it doesn't look like I have the option to git clone (https://mafft.cbrc.jp/alignment/software/source.html). Would you mind lending a hand with this program / advising on installation? If we can get this on I think we're pretty much set!

**Comment by apome** [comment]
Hi @yuvipanda, how are you? I think we're good on most installed programs, but wanted to ask you a quick question about one of them (wtdbg2, https://github.com/ruanjue/wtdbg2). Executing 'wtdbg2' works for the first step, then in that package there should be a command called wtpoa-cns, but I can't seem to locate it. Is there an easy way to access the location of where this was installed? Thanks a bunch,
<img width="532" alt="Screen Shot 2019-05-14 at 5 21 27 PM" src="https://user-images.githubusercontent.com/26755340/57740667-d0511b80-766d-11e9-9655-759bdd384167.png">

**Comment by yuvipanda** [comment]
@apome https://github.com/berkeley-dsep-infra/datahub/pull/717 adds wtpoa-cns to it. https://github.com/berkeley-dsep-infra/datahub/pull/718 adds the suite of stuff from mafft. Let me know if that works, @apome.

**Comment by apome** [comment]
Thanks a ton @yuvipanda - the wtpoa-cns command now works great!
For mafft I'm getting bin/sh: 1: mafft: not found - perhaps there's something I'm missing to find a mafftdir subfolder that contains mafft.bat script (https://mafft.cbrc.jp/alignment/software/linuxportable.html). This isn't critical to the course, as we can perform MAFFT on a GUI or online server, so no worries if it's a hassle getting this one on. Thanks again for your help,

**Comment by yuvipanda** [comment]
@apome you can see the script that builds and sets this up in https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/genomics-su2019/image/postBuild. Let me know / make a PR if you know how else it should be set up.

Hope the class goes well! Let me know if there's anything we should do. I know you have a 4G Memory allocation, do your students need that too?

**Comment by yuvipanda** [comment]
I heard from @ericvd-ucb that the class has finished, so I'm going to tear down the hub. I'll keep the user's data for a while though.

@apome if you can tell us a few things that would've made this easier and work better for you, I'm all ears.
