### ISSUE TITLE
Unable to delete nonempty folders

### ISSUE THREAD

**Issue by mowilk** [berkeley-dsep-infra/datahub#998]
Not sure if this is intended or not, but trying to delete a nonempty folder using the graphic file browser prompts the message: "A directory must be empty before being deleted." Using rm -rf in terminal works fine.

**Comment by yuvipanda** [comment]
Thanks for opening this, @mowilk.

From https://github.com/jupyter/notebook/issues/2760 and issues linked from there, if [send2trash](https://pypi.org/project/Send2Trash/) is not installed, you can't delete non-empty folders. send2trash sends stuff to the 'Recycle Bin' equivalent. Since we don't have that in JupyterHub, it's disabled to prevent people from accidentally deleting entire directories with no way to recover them. This seems like a reasonable tradeoff to me, so I'd say it is intended?

JupyterLab might have a way to delete recursively in the UI, but in the meantime I'd recommend using rm -rf if you have to. 

Hope this helps!

**Comment by Dmitry1987** [comment]
@yuvipanda isn't it only relevant for Notebook, and not jupyterhub? (hub just spawns a notebook?)
an ugly hack is to patch a file that's responsible for send2trash, https://github.com/jupyter/notebook/issues/4916  i have no idea how to do it otherwise.

But what do you mean it's disabled in jupyterhub?  like, if I include this package in hub server, it can be enabled in all notebooks and will work or something? :O  I don't think the hub is one that runs the delete operation in any case, it can only affect the settings of spawned Notebooks, unless they're overridden with custom config (which I did, and enabled the send2trash, then disabled, nothing works)
